version: 2.1

jobs:
  setup-environment:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: make setup (via Makefile)
          command: |
            make setup
      - run:
          name: make install (via Makefile)
          command: |
            make install
      - run:
          name: make lint (via Makefile)
          command: |
            make lint
  build-docker:
    docker:
      - image: docker:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
            apk update && apk add bash
      - run:
          name: build docker (via Dockerfile)
          command: |
            sh ./run_docker.sh
            sh ./upload_docker.sh
  deploy-eks:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      # - run: yum -y install tar gzip
      - run: apk add --update tar gzip nodejs npm curl 
      - run: pip install awscli
      - run: aws --version
      - run:
          name: install aws eks
          command: |
            sh ./install_eksctl.sh
      - run:
          name: install kubectl
          command: |
            sh ./install_kubectl.sh




workflows:
  captone:
    jobs:
      - setup-environment
      - build-docker:
          requires: [setup-environment]
      - deploy-eks:
          requires: [build-docker]