version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.2.0
jobs:
  setup-environment:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: make setup (via Makefile)
          command: |
            make setup
      - run:
          name: make install (via Makefile)
          command: |
            make install
      - run:
          name: make lint (via Makefile)
          command: |
            make lint
  build-docker:
    docker:
      - image: docker:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
            apk update && apk add bash
      - run:
          name: build docker (via Dockerfile)
          command: |
            sh ./run_docker.sh
            sh ./upload_docker.sh
  deploy-eks:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - apk add --update tar gzip nodejs npm curl
      - pip install awscli
      - aws --version
      - run:
        name: install eksctl
        command: |
          #curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          #sudo mv /tmp/eksctl /usr/local/bin
          eksctl --version




workflows:
  captone:
    jobs:
      - setup-environment
      - build-docker:
          requires: [setup-environment]
      - deploy-eks:
          requires: [build-docker]